# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build_win:
    name: Building Windows Candor 
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: '14.0.0'
        java-package: jdk
        architecture: x64
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew packageCandor
    - uses: actions/upload-artifact@v2
      with:
        name: CandorManager-win
        path: build/packaged/CandorModManager.zip
  
  build_linux:

    name: Building Linux Candor 
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: '14.0.0'
        java-package: jdk
        architecture: x64
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew packageCandor
    - uses: actions/upload-artifact@v2
      with:
        name: CandorManager-linux
        path: build/packaged/CandorModManager.zip

  build_mac:

    name: Building MacOS Candor 
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: '14.0.0'
        java-package: jdk
        architecture: x64
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew packageCandor
    - uses: actions/upload-artifact@v2
      with:
        name: CandorManager-mac
        path: build/packaged/CandorModManager.zip
